/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ['./src/**/*.{js,jsx}'],
  theme: {
    extend: {
      opacity: {
        45: '0.45',
      },
      borderOpacity: {
        65: '0.65',
      },
      fontFamily: {
        satoshiRegular: ['Satoshi Regular'],
        satoshiMedium: ['Satoshi Medium'],
        satoshiBold: ['Satoshi Bold'],
        satoshiBlack: ['Satoshi Black'],
        satoshiLight: ['Satoshi Light'],
        jostSemibold: ['Jost SemiBold'],
        jostBold: ['Jost Bold'],
        jostRegular: ['Jost Regular'],
      },
      colors: {
        WhiteLilac: '#F4F7FA',
        CadetGrey: '#909EB4',
        BlueJay: '#3C567E',
        primary: '#0E1438',
        accent: '#80E4EE',
        white: '#FFFFFF',
        grey: '#F1F4F8',
        light_grey: 'rgba(255, 255, 255, 0.6)',
        green: '#55D0B3',
        dark_acent: '#61C9DB',
        light_white: '#F6F8FB',
        footer_txt: '#141C4C',
        footer_head: '#39C2DF',
        grey_white: '#0B0B0B',
        black: '#000000',
        Verdigris: '#33B0AA',
        DarkSlateGrey: '#293344',
        DarkGrey: '#363636',
        Harp: '#EBEEF2',
        Dusk: '#3E577E',
        primary: '#0E1438',
        accent: '#80E4EE',
        white: '#FFFFFF',
        grey: '#F1F4F8',
        light_grey: 'rgba(255, 255, 255, 0.6)',
        green: '#55D0B3',
        dark_acent: '#61C9DB',
        light_white: '#F6F8FB',
        footer_txt: '#141C4C',
        footer_head: '#39C2DF',
        grey_white: '#0B0B0B',
        black: '#000000',
        blueShadow: '#3C567E',
        highlight: '#10A39B',
        secondaryLight: '#909EB4',
        cyanHeading: '#129C9C',
        Porcelain: '#EAF0F5',
        Kimberly: '#5B6082',
      },
    },
  },
  plugins: [],
}
